image: docker:20
services:
  - name: docker:20.10.6-dind

stages:
  - test
  - build

test project:
    stage: test
    image: node:16
    script:
      - npm install
      - npm test

build project:
  stage: build
  image: node:16
  script:
    - npm install
    - npm build